// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/szpp-dev-team/szpp-judge/backend/domain/repository/ent/predicate"
	"github.com/szpp-dev-team/szpp-judge/backend/domain/repository/ent/task"
	"github.com/szpp-dev-team/szpp-judge/backend/domain/repository/ent/testcase"
	"github.com/szpp-dev-team/szpp-judge/backend/domain/repository/ent/testcaseset"
)

// TestcaseSetUpdate is the builder for updating TestcaseSet entities.
type TestcaseSetUpdate struct {
	config
	hooks    []Hook
	mutation *TestcaseSetMutation
}

// Where appends a list predicates to the TestcaseSetUpdate builder.
func (tsu *TestcaseSetUpdate) Where(ps ...predicate.TestcaseSet) *TestcaseSetUpdate {
	tsu.mutation.Where(ps...)
	return tsu
}

// SetName sets the "name" field.
func (tsu *TestcaseSetUpdate) SetName(s string) *TestcaseSetUpdate {
	tsu.mutation.SetName(s)
	return tsu
}

// SetScoreRatio sets the "score_ratio" field.
func (tsu *TestcaseSetUpdate) SetScoreRatio(i int) *TestcaseSetUpdate {
	tsu.mutation.ResetScoreRatio()
	tsu.mutation.SetScoreRatio(i)
	return tsu
}

// AddScoreRatio adds i to the "score_ratio" field.
func (tsu *TestcaseSetUpdate) AddScoreRatio(i int) *TestcaseSetUpdate {
	tsu.mutation.AddScoreRatio(i)
	return tsu
}

// SetIsSample sets the "is_sample" field.
func (tsu *TestcaseSetUpdate) SetIsSample(b bool) *TestcaseSetUpdate {
	tsu.mutation.SetIsSample(b)
	return tsu
}

// SetCreatedAt sets the "created_at" field.
func (tsu *TestcaseSetUpdate) SetCreatedAt(t time.Time) *TestcaseSetUpdate {
	tsu.mutation.SetCreatedAt(t)
	return tsu
}

// SetUpdatedAt sets the "updated_at" field.
func (tsu *TestcaseSetUpdate) SetUpdatedAt(t time.Time) *TestcaseSetUpdate {
	tsu.mutation.SetUpdatedAt(t)
	return tsu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tsu *TestcaseSetUpdate) SetNillableUpdatedAt(t *time.Time) *TestcaseSetUpdate {
	if t != nil {
		tsu.SetUpdatedAt(*t)
	}
	return tsu
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (tsu *TestcaseSetUpdate) ClearUpdatedAt() *TestcaseSetUpdate {
	tsu.mutation.ClearUpdatedAt()
	return tsu
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (tsu *TestcaseSetUpdate) SetTaskID(id int) *TestcaseSetUpdate {
	tsu.mutation.SetTaskID(id)
	return tsu
}

// SetTask sets the "task" edge to the Task entity.
func (tsu *TestcaseSetUpdate) SetTask(t *Task) *TestcaseSetUpdate {
	return tsu.SetTaskID(t.ID)
}

// AddTestcaseIDs adds the "testcases" edge to the Testcase entity by IDs.
func (tsu *TestcaseSetUpdate) AddTestcaseIDs(ids ...int) *TestcaseSetUpdate {
	tsu.mutation.AddTestcaseIDs(ids...)
	return tsu
}

// AddTestcases adds the "testcases" edges to the Testcase entity.
func (tsu *TestcaseSetUpdate) AddTestcases(t ...*Testcase) *TestcaseSetUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tsu.AddTestcaseIDs(ids...)
}

// Mutation returns the TestcaseSetMutation object of the builder.
func (tsu *TestcaseSetUpdate) Mutation() *TestcaseSetMutation {
	return tsu.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (tsu *TestcaseSetUpdate) ClearTask() *TestcaseSetUpdate {
	tsu.mutation.ClearTask()
	return tsu
}

// ClearTestcases clears all "testcases" edges to the Testcase entity.
func (tsu *TestcaseSetUpdate) ClearTestcases() *TestcaseSetUpdate {
	tsu.mutation.ClearTestcases()
	return tsu
}

// RemoveTestcaseIDs removes the "testcases" edge to Testcase entities by IDs.
func (tsu *TestcaseSetUpdate) RemoveTestcaseIDs(ids ...int) *TestcaseSetUpdate {
	tsu.mutation.RemoveTestcaseIDs(ids...)
	return tsu
}

// RemoveTestcases removes "testcases" edges to Testcase entities.
func (tsu *TestcaseSetUpdate) RemoveTestcases(t ...*Testcase) *TestcaseSetUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tsu.RemoveTestcaseIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tsu *TestcaseSetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tsu.sqlSave, tsu.mutation, tsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tsu *TestcaseSetUpdate) SaveX(ctx context.Context) int {
	affected, err := tsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tsu *TestcaseSetUpdate) Exec(ctx context.Context) error {
	_, err := tsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsu *TestcaseSetUpdate) ExecX(ctx context.Context) {
	if err := tsu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tsu *TestcaseSetUpdate) check() error {
	if _, ok := tsu.mutation.TaskID(); tsu.mutation.TaskCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "TestcaseSet.task"`)
	}
	return nil
}

func (tsu *TestcaseSetUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tsu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(testcaseset.Table, testcaseset.Columns, sqlgraph.NewFieldSpec(testcaseset.FieldID, field.TypeInt))
	if ps := tsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tsu.mutation.Name(); ok {
		_spec.SetField(testcaseset.FieldName, field.TypeString, value)
	}
	if value, ok := tsu.mutation.ScoreRatio(); ok {
		_spec.SetField(testcaseset.FieldScoreRatio, field.TypeInt, value)
	}
	if value, ok := tsu.mutation.AddedScoreRatio(); ok {
		_spec.AddField(testcaseset.FieldScoreRatio, field.TypeInt, value)
	}
	if value, ok := tsu.mutation.IsSample(); ok {
		_spec.SetField(testcaseset.FieldIsSample, field.TypeBool, value)
	}
	if value, ok := tsu.mutation.CreatedAt(); ok {
		_spec.SetField(testcaseset.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := tsu.mutation.UpdatedAt(); ok {
		_spec.SetField(testcaseset.FieldUpdatedAt, field.TypeTime, value)
	}
	if tsu.mutation.UpdatedAtCleared() {
		_spec.ClearField(testcaseset.FieldUpdatedAt, field.TypeTime)
	}
	if tsu.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   testcaseset.TaskTable,
			Columns: []string{testcaseset.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tsu.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   testcaseset.TaskTable,
			Columns: []string{testcaseset.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tsu.mutation.TestcasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   testcaseset.TestcasesTable,
			Columns: testcaseset.TestcasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testcase.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tsu.mutation.RemovedTestcasesIDs(); len(nodes) > 0 && !tsu.mutation.TestcasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   testcaseset.TestcasesTable,
			Columns: testcaseset.TestcasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testcase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tsu.mutation.TestcasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   testcaseset.TestcasesTable,
			Columns: testcaseset.TestcasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testcase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{testcaseset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tsu.mutation.done = true
	return n, nil
}

// TestcaseSetUpdateOne is the builder for updating a single TestcaseSet entity.
type TestcaseSetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TestcaseSetMutation
}

// SetName sets the "name" field.
func (tsuo *TestcaseSetUpdateOne) SetName(s string) *TestcaseSetUpdateOne {
	tsuo.mutation.SetName(s)
	return tsuo
}

// SetScoreRatio sets the "score_ratio" field.
func (tsuo *TestcaseSetUpdateOne) SetScoreRatio(i int) *TestcaseSetUpdateOne {
	tsuo.mutation.ResetScoreRatio()
	tsuo.mutation.SetScoreRatio(i)
	return tsuo
}

// AddScoreRatio adds i to the "score_ratio" field.
func (tsuo *TestcaseSetUpdateOne) AddScoreRatio(i int) *TestcaseSetUpdateOne {
	tsuo.mutation.AddScoreRatio(i)
	return tsuo
}

// SetIsSample sets the "is_sample" field.
func (tsuo *TestcaseSetUpdateOne) SetIsSample(b bool) *TestcaseSetUpdateOne {
	tsuo.mutation.SetIsSample(b)
	return tsuo
}

// SetCreatedAt sets the "created_at" field.
func (tsuo *TestcaseSetUpdateOne) SetCreatedAt(t time.Time) *TestcaseSetUpdateOne {
	tsuo.mutation.SetCreatedAt(t)
	return tsuo
}

// SetUpdatedAt sets the "updated_at" field.
func (tsuo *TestcaseSetUpdateOne) SetUpdatedAt(t time.Time) *TestcaseSetUpdateOne {
	tsuo.mutation.SetUpdatedAt(t)
	return tsuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tsuo *TestcaseSetUpdateOne) SetNillableUpdatedAt(t *time.Time) *TestcaseSetUpdateOne {
	if t != nil {
		tsuo.SetUpdatedAt(*t)
	}
	return tsuo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (tsuo *TestcaseSetUpdateOne) ClearUpdatedAt() *TestcaseSetUpdateOne {
	tsuo.mutation.ClearUpdatedAt()
	return tsuo
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (tsuo *TestcaseSetUpdateOne) SetTaskID(id int) *TestcaseSetUpdateOne {
	tsuo.mutation.SetTaskID(id)
	return tsuo
}

// SetTask sets the "task" edge to the Task entity.
func (tsuo *TestcaseSetUpdateOne) SetTask(t *Task) *TestcaseSetUpdateOne {
	return tsuo.SetTaskID(t.ID)
}

// AddTestcaseIDs adds the "testcases" edge to the Testcase entity by IDs.
func (tsuo *TestcaseSetUpdateOne) AddTestcaseIDs(ids ...int) *TestcaseSetUpdateOne {
	tsuo.mutation.AddTestcaseIDs(ids...)
	return tsuo
}

// AddTestcases adds the "testcases" edges to the Testcase entity.
func (tsuo *TestcaseSetUpdateOne) AddTestcases(t ...*Testcase) *TestcaseSetUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tsuo.AddTestcaseIDs(ids...)
}

// Mutation returns the TestcaseSetMutation object of the builder.
func (tsuo *TestcaseSetUpdateOne) Mutation() *TestcaseSetMutation {
	return tsuo.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (tsuo *TestcaseSetUpdateOne) ClearTask() *TestcaseSetUpdateOne {
	tsuo.mutation.ClearTask()
	return tsuo
}

// ClearTestcases clears all "testcases" edges to the Testcase entity.
func (tsuo *TestcaseSetUpdateOne) ClearTestcases() *TestcaseSetUpdateOne {
	tsuo.mutation.ClearTestcases()
	return tsuo
}

// RemoveTestcaseIDs removes the "testcases" edge to Testcase entities by IDs.
func (tsuo *TestcaseSetUpdateOne) RemoveTestcaseIDs(ids ...int) *TestcaseSetUpdateOne {
	tsuo.mutation.RemoveTestcaseIDs(ids...)
	return tsuo
}

// RemoveTestcases removes "testcases" edges to Testcase entities.
func (tsuo *TestcaseSetUpdateOne) RemoveTestcases(t ...*Testcase) *TestcaseSetUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tsuo.RemoveTestcaseIDs(ids...)
}

// Where appends a list predicates to the TestcaseSetUpdate builder.
func (tsuo *TestcaseSetUpdateOne) Where(ps ...predicate.TestcaseSet) *TestcaseSetUpdateOne {
	tsuo.mutation.Where(ps...)
	return tsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tsuo *TestcaseSetUpdateOne) Select(field string, fields ...string) *TestcaseSetUpdateOne {
	tsuo.fields = append([]string{field}, fields...)
	return tsuo
}

// Save executes the query and returns the updated TestcaseSet entity.
func (tsuo *TestcaseSetUpdateOne) Save(ctx context.Context) (*TestcaseSet, error) {
	return withHooks(ctx, tsuo.sqlSave, tsuo.mutation, tsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tsuo *TestcaseSetUpdateOne) SaveX(ctx context.Context) *TestcaseSet {
	node, err := tsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tsuo *TestcaseSetUpdateOne) Exec(ctx context.Context) error {
	_, err := tsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsuo *TestcaseSetUpdateOne) ExecX(ctx context.Context) {
	if err := tsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tsuo *TestcaseSetUpdateOne) check() error {
	if _, ok := tsuo.mutation.TaskID(); tsuo.mutation.TaskCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "TestcaseSet.task"`)
	}
	return nil
}

func (tsuo *TestcaseSetUpdateOne) sqlSave(ctx context.Context) (_node *TestcaseSet, err error) {
	if err := tsuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(testcaseset.Table, testcaseset.Columns, sqlgraph.NewFieldSpec(testcaseset.FieldID, field.TypeInt))
	id, ok := tsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TestcaseSet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, testcaseset.FieldID)
		for _, f := range fields {
			if !testcaseset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != testcaseset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tsuo.mutation.Name(); ok {
		_spec.SetField(testcaseset.FieldName, field.TypeString, value)
	}
	if value, ok := tsuo.mutation.ScoreRatio(); ok {
		_spec.SetField(testcaseset.FieldScoreRatio, field.TypeInt, value)
	}
	if value, ok := tsuo.mutation.AddedScoreRatio(); ok {
		_spec.AddField(testcaseset.FieldScoreRatio, field.TypeInt, value)
	}
	if value, ok := tsuo.mutation.IsSample(); ok {
		_spec.SetField(testcaseset.FieldIsSample, field.TypeBool, value)
	}
	if value, ok := tsuo.mutation.CreatedAt(); ok {
		_spec.SetField(testcaseset.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := tsuo.mutation.UpdatedAt(); ok {
		_spec.SetField(testcaseset.FieldUpdatedAt, field.TypeTime, value)
	}
	if tsuo.mutation.UpdatedAtCleared() {
		_spec.ClearField(testcaseset.FieldUpdatedAt, field.TypeTime)
	}
	if tsuo.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   testcaseset.TaskTable,
			Columns: []string{testcaseset.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tsuo.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   testcaseset.TaskTable,
			Columns: []string{testcaseset.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tsuo.mutation.TestcasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   testcaseset.TestcasesTable,
			Columns: testcaseset.TestcasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testcase.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tsuo.mutation.RemovedTestcasesIDs(); len(nodes) > 0 && !tsuo.mutation.TestcasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   testcaseset.TestcasesTable,
			Columns: testcaseset.TestcasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testcase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tsuo.mutation.TestcasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   testcaseset.TestcasesTable,
			Columns: testcaseset.TestcasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(testcase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TestcaseSet{config: tsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{testcaseset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tsuo.mutation.done = true
	return _node, nil
}
