// @generated by protobuf-ts 2.9.1
// @generated from protobuf file "backend/v1/services.proto" (package "backend.v1", syntax proto3)
// tslint:disable
import { PingResponse } from "./messages";
import { PingRequest } from "./messages";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service backend.v1.HealthcheckService
 */
export const HealthcheckService = new ServiceType("backend.v1.HealthcheckService", [
    { name: "Ping", options: {}, I: PingRequest, O: PingResponse }
]);
