name: backend
on:
  pull_request:
    branches:
      - develop
    paths:
      - backend/**
      - .github/workflows/backend.yml
defaults:
  run:
    working-directory: ./backend
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v4
        with:
          go-version-file: backend/go.mod
      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.3"
          install-go: false
          cache-key: ${{ matrix.go }}
          working-directory: backend
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: backend/go.mod
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: Format
        run: goimports -w .
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style(backend): [bot] apply code formatter changes"
          ref: ${{ steps.upstreambranch.outputs.branch }}
  test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:11.1
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: szpp-judge-db
          MYSQL_ROOT_PASSWORD: szpp
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: backend/go.mod
      - name: Run tests with coverage report output
        run: go test ./... -coverprofile=coverage.out
      - name: Report coverage
        uses: k1LoW/octocov-action@v0
        with:
          config: backend/.octocov.yml
