name: Deploy to Firebase Hosting on PR merge
on:
  pull_request:
    types:
      - closed
    branches:
      - develop
    paths:
      - frontend/**
      - '!frontend/src/gen/**'
      - .github/workflows/frontend-deploy.yml
defaults:
  run:
    working-directory: ./frontend
jobs:
  build_and_deploy_if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version-file: frontend/.node-version
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.STORE_PATH }}
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('frontend/pnpm-lock.yaml')
            }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Build with lint
        run: pnpm build
        env:
          NEXT_PUBLIC_ENVOY_BASE_URL: ${{ secrets.NEXT_PUBLIC_ENVOY_BASE_URL }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: frontend
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SZPP_JUDGE_3776 }}
          channelId: live # "live" channel means production
          projectId: szpp-judge-3776
