name: Deploy to Firebase Hosting on PR to preview
on:
  pull_request:
    branches:
      - develop
    paths:
      - frontend/**
      - '!frontend/src/gen/**'
      - .github/workflows/frontend-deploy-preview.yml
defaults:
  run:
    working-directory: ./frontend
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version-file: frontend/.node-version

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.STORE_PATH }}
            ${{ github.workspace }}/frontend/.next/cache
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('frontend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build with lint
        run: pnpm build
        env:
          NEXT_PUBLIC_ENVOY_BASE_URL: ${{ secrets.NEXT_PUBLIC_ENVOY_BASE_URL }}

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: frontend
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SZPP_JUDGE_3776 }}'
          expires: 2d
          projectId: szpp-judge-3776
